remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: FENITH
description: "Federated Learning in Dynamic and Heterogeneous Environments for European Digital Healthcare"
baseurl: /FENITH2
show_downloads: true
